import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./storeProvide";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <head>
      <link rel="icon" href="/images/shopping.png" type="image/png" />
    </head>
      <StoreProvider>
      <body className={inter.className}>{children}</body>
      </StoreProvider>
    </html>
  );
}
